import json
#creating dictionary to read to JSON file
capitals = {
    "Alabama":        {"capital": "Montgomery",   "address": "600 Dexter Ave, Montgomery, AL 36130"},
    "Alaska":         {"capital": "Juneau",        "address": "120 4th St, Juneau, AK 99801"},
    "Arizona":        {"capital": "Phoenix",       "address": "1700 W Washington St, Phoenix, AZ 85007"},
    "Arkansas":       {"capital": "Little Rock",   "address": "500 Woodlane St, Little Rock, AR 72201"},
    "California":     {"capital": "Sacramento",    "address": "1315 10th St, Sacramento, CA 95814"},
    "Colorado":       {"capital": "Denver",        "address": "200 E Colfax Ave, Denver, CO 80203"},
    "Connecticut":    {"capital": "Hartford",      "address": "210 Capitol Ave, Hartford, CT 06106"},
    "Delaware":       {"capital": "Dover",         "address": "411 Legislative Ave, Dover, DE 19901"},
    "Florida":        {"capital": "Tallahassee",   "address": "400 S Monroe St, Tallahassee, FL 32399"},
    "Georgia":        {"capital": "Atlanta",       "address": "206 Washington St SW, Atlanta, GA 30334"},
    "Hawaii":         {"capital": "Honolulu",      "address": "415 S Beretania St, Honolulu, HI 96813"},
    "Idaho":          {"capital": "Boise",         "address": "700 W Jefferson St, Boise, ID 83720"},
    "Illinois":       {"capital": "Springfield",   "address": "401 S 2nd St, Springfield, IL 62701"},
    "Indiana":        {"capital": "Indianapolis",  "address": "200 W Washington St, Indianapolis, IN 46204"},
    "Iowa":           {"capital": "Des Moines",    "address": "1007 E Grand Ave, Des Moines, IA 50319"},
    "Kansas":         {"capital": "Topeka",        "address": "300 SW 10th Ave, Topeka, KS 66612"},
    "Kentucky":       {"capital": "Frankfort",     "address": "700 Capitol Ave, Frankfort, KY 40601"},
    "Louisiana":      {"capital": "Baton Rouge",   "address": "900 N 3rd St, Baton Rouge, LA 70804"},
    "Maine":          {"capital": "Augusta",       "address": "210 State St, Augusta, ME 04333"},
    "Maryland":       {"capital": "Annapolis",     "address": "100 State Cir, Annapolis, MD 21401"},
    "Massachusetts":  {"capital": "Boston",        "address": "24 Beacon St, Boston, MA 02133"},
    "Michigan":       {"capital": "Lansing",       "address": "100 N Capitol Ave, Lansing, MI 48933"},
    "Minnesota":      {"capital": "Saint Paul",    "address": "75 Rev Dr Martin Luther King Jr Blvd, Saint Paul, MN 55155"},
    "Mississippi":    {"capital": "Jackson",       "address": "400 High St, Jackson, MS 39201"},
    "Missouri":       {"capital": "Jefferson City","address": "201 W Capitol Ave, Jefferson City, MO 65101"},
    "Montana":        {"capital": "Helena",        "address": "1301 E 6th Ave, Helena, MT 59601"},
    "Nebraska":       {"capital": "Lincoln",       "address": "1445 K St, Lincoln, NE 68508"},
    "Nevada":         {"capital": "Carson City",   "address": "101 N Carson St, Carson City, NV 89701"},
    "New Hampshire":  {"capital": "Concord",       "address": "107 N Main St, Concord, NH 03301"},
    "New Jersey":     {"capital": "Trenton",       "address": "125 W State St, Trenton, NJ 08608"},
    "New Mexico":     {"capital": "Santa Fe",      "address": "490 Old Santa Fe Trail, Santa Fe, NM 87501"},
    "New York":       {"capital": "Albany",        "address": "State St & Washington Ave, Albany, NY 12224"},
    "North Carolina": {"capital": "Raleigh",       "address": "1 E Edenton St, Raleigh, NC 27601"},
    "North Dakota":   {"capital": "Bismarck",      "address": "600 E Boulevard Ave, Bismarck, ND 58505"},
    "Ohio":           {"capital": "Columbus",      "address": "1 Capitol Square, Columbus, OH 43215"},
    "Oklahoma":       {"capital": "Oklahoma City", "address": "2300 N Lincoln Blvd, Oklahoma City, OK 73105"},
    "Oregon":         {"capital": "Salem",         "address": "900 Court St NE, Salem, OR 97301"},
    "Pennsylvania":   {"capital": "Harrisburg",    "address": "501 N 3rd St, Harrisburg, PA 17120"},
    "Rhode Island":   {"capital": "Providence",    "address": "82 Smith St, Providence, RI 02903"},
    "South Carolina": {"capital": "Columbia",      "address": "1100 Gervais St, Columbia, SC 29201"},
    "South Dakota":   {"capital": "Pierre",        "address": "500 E Capitol Ave, Pierre, SD 57501"},
    "Tennessee":      {"capital": "Nashville",     "address": "600 Dr Martin Luther King Jr Blvd, Nashville, TN 37243"},
    "Texas":          {"capital": "Austin",        "address": "1100 Congress Ave, Austin, TX 78701"},
    "Utah":           {"capital": "Salt Lake City","address": "350 N State St, Salt Lake City, UT 84114"},
    "Vermont":        {"capital": "Montpelier",    "address": "115 State St, Montpelier, VT 05633"},
    "Virginia":       {"capital": "Richmond",      "address": "1000 Bank St, Richmond, VA 23219"},
    "Washington":     {"capital": "Olympia",       "address": "416 Sid Snyder Ave SW, Olympia, WA 98504"},
    "West Virginia":  {"capital": "Charleston",    "address": "1900 Kanawha Blvd E, Charleston, WV 25305"},
    "Wisconsin":      {"capital": "Madison",       "address": "2 E Main St, Madison, WI 53703"},
    "Wyoming":        {"capital": "Cheyenne",      "address": "200 W 24th St, Cheyenne, WY 82002"},
}

#reading to JSON file, indenting for readability
with open("usa_state_capitals.json", "w") as f:
    json.dump(capitals, f, indent = 4)
